### ISSUE TITLE
Thunderbird 78

### ISSUE THREAD

**Issue by gitman0** [voccs/folderflags#6]
I'm able to install to install the addon in Thunderbird 78, but the Flags tab on the Folder Properties dialog is missing. According to https://developer.thunderbird.net/add-ons/updating/tb78, XUL overlays are no longer supported. Any plans to update this useful addon?

Alternatively, is there a method to set these flags manually (ie. developer console, or editing a file)?

Thanks

**Comment by voccs** [comment]
My support of this add-on is pretty casual these days.  Last I looked, the Thunderbird developers are taking an inscrutable path from the old homegrown XUL plugin environment to whatever the final architecture of add-ons will look like, with documentation behind the times or not at all and, most importantly, APIs missing wholesale.  It's understandably not a simple transition, but I would consider trying to keep up with the shifting environment to be a waste of time.

I may revisit this when APIs are more stable, but in the brief window I checked in on things, it was in the messy phase.

I'm afraid I don't know what the current flag mechanism looks like in TB78.

**Comment by bege10** [comment]
If it was the same as before and only the xul overlay does not work, how will it work with Javascript? What is the code and how to find out the folder name? I already looked at the code of the addon but don't understand it.

**Comment by itagagaki** [comment]
Hello
I think I can probably make this add-on TB78 compatible. If I make a pull request, will you accept it?
If no, may I release it with my standalone repository under a different name?

**Comment by voccs** [comment]
I would absolutely accept a pull request, yes.

**Comment by itagagaki** [comment]
I made pull request #7
Thanks

**Comment by bege10** [comment]
> 
> 
> I would absolutely accept a pull request, yes.

@voccs Hello,
would you, please, merge the pull request and provide an update of FolderFlags on addons.thunderbird.net?
Thank you very much. ❤️

**Comment by bege10** [comment]
@voccs Thank you so much! 🚀

**Comment by douglaswth** [comment]
It seems like this was working correctly with v1.4.0, but has regressed to not showing in v1.4.1.

**Comment by bege10** [comment]
> 
> 
> It seems like this was working correctly with v1.4.0, but has regressed to not showing in v1.4.1.

Works correct here on Windows 10 Professional 64 bit with TB 78.10.2, German locale

**Comment by douglaswth** [comment]
Given that the changes between v1.4.0 and v1.4.1 seem to be around locales and I am seeing the issue with the English locale, perhaps it may be isolated to only some locales.

**Comment by bege10** [comment]
> 
> 
> Given that the changes between v1.4.0 and v1.4.1 seem to be around locales and I am seeing the issue with the English (United States) locale, perhaps it may be isolated to only some locales.

That's what I had in mind when I added "German locale".

**Comment by jobisoft** [comment]
@douglaswth :  Hm, I am sorry if my merge request for the locales caused issues. What is the error you get?

**Comment by jobisoft** [comment]
This should fix it:
https://github.com/voccs/folderflags/pull/9

**Comment by voccs** [comment]
Thanks all for helping make this happen.  As for the latest, I've made a 1.4.2 submission with @jobisoft's #9 work merged in.

Closing this issue out, feel free to open a new one if anything else comes up.
